// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_ from "./routes/[slug].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $test from "./routes/test.tsx";
import * as $Context from "./islands/Context.tsx";
import * as $Form1 from "./islands/Form1.tsx";
import * as $Form2 from "./islands/Form2.tsx";
import * as $test_1 from "./islands/test.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $_slug_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/test.tsx": $test,
  },
  islands: {
    "./islands/Context.tsx": $Context,
    "./islands/Form1.tsx": $Form1,
    "./islands/Form2.tsx": $Form2,
    "./islands/test.tsx": $test_1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
